version: '3.8'

services:
  api-service:
    image: luongquoctay87/sample-java-app:v1.0.0
    container_name: api-service
#    environment:
#      - MYSQL_URL=${MYSQL_URL}
#      - MYSQL_PORT=${MYSQL_PORT}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - ./.evn
    ports:
      - "8080:8080"
    networks:
      - backend

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: "grafana/grafana"
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    name: api-network
